<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" dir="{{ in_array(app()->getLocale(), ['fa', 'ar'], true) ? 'rtl' : 'ltr' }}" class="h-full" x-data="{ dark: localStorage.getItem('hc-theme') === 'dark' }" x-init="$watch('dark', value => localStorage.setItem('hc-theme', value ? 'dark' : 'light'))" :class="{ 'dark': dark }">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="description" content="{{ __('Find, buy, sell or rent property in North Cyprus with a multilingual AI real estate advisor.') }}">
    <link rel="canonical" href="{{ url('/') }}">
    <meta property="og:title" content="HomeCyp AI — {{ __('North Cyprus property advisor') }}">
    <meta property="og:description" content="{{ __('Find, buy, sell or rent property in North Cyprus with a multilingual AI real estate advisor.') }}">
    <meta property="og:url" content="{{ url('/') }}">
    <meta property="og:type" content="website">
    <title>HomeCyp AI — {{ __('North Cyprus property advisor') }}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@500;600;700&family=Noto+Sans+Arabic:wght@400;500;600;700&display=swap" rel="stylesheet">
    @vite(['resources/css/app.css'])
    @livewireStyles
    <script type="application/ld+json">{!! json_encode(['@context' => 'https://schema.org', '@type' => 'WebApplication', 'name' => 'HomeCyp AI', 'url' => url('/'), 'applicationCategory' => 'RealEstateApplication', 'availableLanguage' => ['English','Turkish','Persian','Arabic','Russian','German']], JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE) !!}</script>
    <style>
        :root { --hc-bg:#f7f8f6;--hc-surface:#fff;--hc-sidebar:#f0f2ef;--hc-primary:#123f3b;--hc-primary-hover:#0b312e;--hc-primary-contrast:#fff;--hc-accent:#d7a94b;--hc-accent-soft:#fbf3df;--hc-coral:#d85f45;--hc-text:#18211f;--hc-text-secondary:#65716d;--hc-muted:#8b9591;--hc-border:#dde2de;--hc-input:#fff;--hc-hover:#e7ebe7;--hc-focus-ring:rgba(18,63,59,.22);--hc-shadow:0 16px 50px rgba(18,43,39,.08);--font-display:'Manrope','Noto Sans Arabic',sans-serif;--font-body:'DM Sans','Noto Sans Arabic',sans-serif }
        html.dark { --hc-bg:#111715;--hc-surface:#19201e;--hc-sidebar:#151b19;--hc-primary:#d8b768;--hc-primary-hover:#e2c57e;--hc-primary-contrast:#17201d;--hc-accent:#e1bb67;--hc-accent-soft:#302a1d;--hc-coral:#ef826b;--hc-text:#edf1ee;--hc-text-secondary:#aeb9b5;--hc-muted:#7d8985;--hc-border:#2b3532;--hc-input:#202825;--hc-hover:#26302d;--hc-focus-ring:rgba(225,187,103,.3);--hc-shadow:0 18px 60px rgba(0,0,0,.3) }
        *{scrollbar-width:thin;scrollbar-color:var(--hc-border) transparent} body{margin:0;font-family:var(--font-body);background:var(--hc-bg);color:var(--hc-text);-webkit-font-smoothing:antialiased}[dir=rtl] body{font-family:'Noto Sans Arabic',var(--font-body)}button,input,textarea,select{font:inherit}.hc-font-display{font-family:var(--font-display);letter-spacing:-.025em}.hc-surface{background:var(--hc-surface);border-color:var(--hc-border)}.hc-primary-bg{background:var(--hc-primary);color:var(--hc-primary-contrast)}.hc-primary-bg:hover{background:var(--hc-primary-hover)}.hc-accent-text{color:var(--hc-accent)}.hc-text-secondary{color:var(--hc-text-secondary)}.hc-border{border-color:var(--hc-border)}.hc-shadow{box-shadow:var(--hc-shadow)}.hc-focusable:focus-visible{outline:0;box-shadow:0 0 0 3px var(--hc-focus-ring)}
        .hc-icon-button{width:2.5rem;height:2.5rem;display:inline-flex;align-items:center;justify-content:center;border-radius:.75rem;transition:background .18s,color .18s,transform .18s}.hc-icon-button:hover{background:var(--hc-hover);color:var(--hc-text)}.hc-suggestion-card{min-height:116px;display:flex;flex-direction:column;justify-content:space-between;gap:1rem;border:1px solid var(--hc-border);border-radius:1rem;padding:1rem;text-align:start;background:color-mix(in srgb,var(--hc-surface) 94%,var(--hc-accent) 6%);color:var(--hc-text);transition:transform .2s,border-color .2s,box-shadow .2s}.hc-suggestion-card:hover{transform:translateY(-3px);border-color:color-mix(in srgb,var(--hc-accent) 70%,var(--hc-border));box-shadow:0 12px 30px rgba(18,43,39,.08)}
        .hc-chip,.hc-chip-light{border-radius:999px;font-size:.875rem;padding:.48rem .85rem;transition:all .18s}.hc-chip{border:1px solid var(--hc-primary);color:var(--hc-primary);background:transparent;font-weight:600}.hc-chip:hover{background:var(--hc-primary);color:var(--hc-primary-contrast)}.hc-chip-light{border:1px solid var(--hc-border);color:var(--hc-text-secondary);background:var(--hc-surface)}.hc-chip-light:hover{border-color:var(--hc-accent);color:var(--hc-text)}.hc-composer{background:var(--hc-input);border:1px solid var(--hc-border);border-radius:1.5rem;box-shadow:0 8px 35px rgba(25,50,45,.09);transition:border-color .2s,box-shadow .2s}.hc-composer:focus-within{border-color:color-mix(in srgb,var(--hc-primary) 55%,var(--hc-border));box-shadow:0 0 0 3px var(--hc-focus-ring),0 10px 40px rgba(25,50,45,.1)}
        .hc-typing-dot{width:.42rem;height:.42rem;background:var(--hc-text-secondary);border-radius:50%;display:inline-block;animation:hc-bounce 1.25s infinite}.hc-typing-dot:nth-child(2){animation-delay:.14s}.hc-typing-dot:nth-child(3){animation-delay:.28s}@keyframes hc-bounce{0%,60%,100%{transform:translateY(0);opacity:.35}30%{transform:translateY(-4px);opacity:1}}@keyframes hc-rise{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:none}}.hc-fade-rise,.hc-fade-rise-msg{animation:hc-rise .32s ease-out both}.hc-tabular{font-variant-numeric:tabular-nums}@media(prefers-reduced-motion:reduce){*,*::before,*::after{animation-duration:.01ms!important;transition-duration:.01ms!important}}
        @media(max-height:760px){.hc-empty-state .w-12.h-12{width:2.5rem;height:2.5rem;margin-bottom:.65rem}.hc-empty-state h1{font-size:1.65rem}.hc-empty-state p.mt-3{margin-top:.4rem;font-size:.9rem;line-height:1.45}.hc-empty-state .mt-4{margin-top:.6rem}.hc-empty-state .mt-9{margin-top:1rem}.hc-suggestion-card{min-height:88px;padding:.75rem;gap:.55rem}.hc-empty-state .hc-suggestion-card .w-9.h-9{width:2rem;height:2rem}}
        @media(max-height:620px){.hc-empty-state .w-12.h-12,.hc-empty-state>div>p:first-of-type,.hc-empty-state .inline-flex{display:none}.hc-empty-state h1{font-size:1.35rem}.hc-empty-state .mt-9{margin-top:.65rem}.hc-suggestion-card{min-height:70px;padding:.6rem}.hc-empty-state .hc-suggestion-card .w-9.h-9{display:none}}
    </style>
</head>
<body class="h-full overflow-hidden">
    <livewire:chat-window />
    <script>
        document.addEventListener('alpine:init',()=>{Alpine.data('voiceInput',()=>({listening:false,recognition:null,lastInputWasVoice:false,init(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return;this.recognition=new R;this.recognition.lang=document.documentElement.lang||navigator.language||'en-US';this.recognition.interimResults=false;this.recognition.onresult=e=>{this.lastInputWasVoice=true;this.$wire.set('input',e.results[0][0].transcript).then(()=>this.$wire.send())};this.recognition.onend=()=>this.listening=false;this.recognition.onerror=()=>this.listening=false;window.addEventListener('reply-received',()=>this.lastInputWasVoice&&this.speakLatestReply())},toggle(){if(!this.recognition)return alert(@json(__('Voice input is not supported in this browser.')));this.listening?this.recognition.stop():this.recognition.start();this.listening=!this.listening},speakLatestReply(){this.lastInputWasVoice=false;if(!window.speechSynthesis)return;const b=document.querySelectorAll('[data-message-role="assistant"]'),last=b[b.length-1];if(!last)return;const u=new SpeechSynthesisUtterance(last.innerText);u.lang=document.documentElement.lang||navigator.language;speechSynthesis.cancel();speechSynthesis.speak(u)}}))});
    </script>
    @livewireScripts
</body>
</html>
