<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { Sparkles, ShieldCheck, Flag, MessageSquare, Activity, Trash2 } from 'lucide-vue-next'
import api from '@/lib/api'

const data = ref<any>({ counts:{}, claims:[], reports:[], inquiries:[], deals:[], events:[] })
const busy = ref(false)
const deal = ref({ business_id:'', title:'', discount_label:'', code:'', ends_at:'', is_active:true })
const event = ref({ title:'', venue:'', starts_at:'', status:'published' })
async function load(){ data.value=(await api.get('/admin/growth')).data }
async function update(kind:string,id:number,status:string){ busy.value=true; try{ await api.put(`/admin/growth/${kind}/${id}`,{status}); await load() }finally{busy.value=false} }
async function addDeal(){ await api.post('/admin/growth/deals',deal.value); deal.value={business_id:'',title:'',discount_label:'',code:'',ends_at:'',is_active:true}; await load() }
async function addEvent(){ await api.post('/admin/growth/events',event.value); event.value={title:'',venue:'',starts_at:'',status:'published'}; await load() }
async function remove(kind:string,id:number){ await api.delete(`/admin/growth/${kind}/${id}`); await load() }
onMounted(load)
</script>
<template>
  <div>
    <header class="mb-6"><p class="text-xs uppercase tracking-[.18em] text-teal-600 flex items-center gap-2"><Sparkles :size="15"/> Platform operations</p><h1 class="text-2xl font-extrabold text-slate-900">Growth & Trust</h1><p class="text-sm text-gray-500 mt-1">Manage ownership, data quality, leads, offers and local events.</p></header>
    <div class="grid grid-cols-2 xl:grid-cols-4 gap-3 mb-7"><div v-for="(value,key) in data.counts" :key="key" class="bg-white rounded-2xl p-4 shadow-sm"><p class="text-xs text-gray-400 capitalize">{{ String(key).replace('_',' ') }}</p><strong class="text-2xl text-slate-900">{{ value }}</strong></div></div>
    <div class="grid xl:grid-cols-2 gap-5">
      <section class="bg-white rounded-3xl p-5 shadow-sm"><h2 class="font-bold flex gap-2 mb-4"><ShieldCheck class="text-teal-600" :size="20"/>Business claims</h2><p v-if="!data.claims.length" class="text-sm text-gray-400">No claims.</p><div v-for="x in data.claims" :key="x.id" class="border-t py-3 text-sm"><b>{{x.business_name}}</b><p class="text-xs text-gray-500">{{x.user_name}} · {{x.email}} · {{x.status}}</p><div v-if="x.status==='pending'" class="flex gap-2 mt-2"><button class="px-3 py-1 rounded-full bg-teal-600 text-white" :disabled="busy" @click="update('claims',x.id,'approved')">Approve</button><button class="px-3 py-1 rounded-full bg-gray-100" @click="update('claims',x.id,'rejected')">Reject</button></div></div></section>
      <section class="bg-white rounded-3xl p-5 shadow-sm"><h2 class="font-bold flex gap-2 mb-4"><Flag class="text-orange-500" :size="20"/>Data reports</h2><p v-if="!data.reports.length" class="text-sm text-gray-400">No reports.</p><div v-for="x in data.reports" :key="x.id" class="border-t py-3 text-sm"><b>{{x.business_name}}</b><p class="text-xs text-gray-500">{{x.reason}} · {{x.details || 'No details'}} · {{x.status}}</p><div v-if="x.status==='pending'" class="flex gap-2 mt-2"><button class="px-3 py-1 rounded-full bg-teal-600 text-white" @click="update('reports',x.id,'resolved')">Resolved</button><button class="px-3 py-1 rounded-full bg-gray-100" @click="update('reports',x.id,'dismissed')">Dismiss</button></div></div></section>
      <section class="bg-white rounded-3xl p-5 shadow-sm"><h2 class="font-bold flex gap-2 mb-4"><MessageSquare class="text-blue-500" :size="20"/>Customer leads</h2><p v-if="!data.inquiries.length" class="text-sm text-gray-400">No inquiries.</p><div v-for="x in data.inquiries" :key="x.id" class="border-t py-3 text-sm"><b>{{x.business_name}} — {{x.type}}</b><p class="text-xs text-gray-500">{{x.name}} · {{x.phone}} · {{x.status}}</p><select class="mt-2 border rounded-lg px-2 py-1 text-xs" :value="x.status" @change="update('inquiries',x.id,($event.target as HTMLSelectElement).value)"><option>new</option><option>contacted</option><option>closed</option></select></div></section>
      <section class="bg-white rounded-3xl p-5 shadow-sm"><h2 class="font-bold flex gap-2 mb-4"><Activity class="text-violet-500" :size="20"/>Create deal</h2><form class="grid gap-2" @submit.prevent="addDeal"><input v-model="deal.business_id" required type="number" placeholder="Business ID" class="border rounded-xl p-2 text-sm"><input v-model="deal.title" required placeholder="Offer title" class="border rounded-xl p-2 text-sm"><div class="grid grid-cols-2 gap-2"><input v-model="deal.discount_label" placeholder="20% OFF" class="border rounded-xl p-2 text-sm"><input v-model="deal.code" placeholder="Promo code" class="border rounded-xl p-2 text-sm"></div><input v-model="deal.ends_at" type="datetime-local" class="border rounded-xl p-2 text-sm"><button class="bg-teal-600 text-white rounded-xl p-2 text-sm font-bold">Publish deal</button></form><div v-for="x in data.deals" :key="x.id" class="border-t mt-3 pt-3 flex justify-between text-sm"><span>{{x.title}} <small class="text-gray-400">{{x.discount_label}}</small></span><button @click="remove('deals',x.id)"><Trash2 :size="15" class="text-red-400"/></button></div></section>
      <section class="bg-white rounded-3xl p-5 shadow-sm xl:col-span-2"><h2 class="font-bold mb-4">Create local event</h2><form class="grid md:grid-cols-4 gap-2" @submit.prevent="addEvent"><input v-model="event.title" required placeholder="Event title" class="border rounded-xl p-2 text-sm"><input v-model="event.venue" placeholder="Venue" class="border rounded-xl p-2 text-sm"><input v-model="event.starts_at" required type="datetime-local" class="border rounded-xl p-2 text-sm"><button class="bg-slate-900 text-white rounded-xl p-2 text-sm font-bold">Publish event</button></form><div class="grid md:grid-cols-2 gap-2 mt-4"><div v-for="x in data.events" :key="x.id" class="border rounded-xl p-3 flex justify-between text-sm"><span><b>{{x.title}}</b><small class="block text-gray-400">{{x.venue}}</small></span><button @click="remove('events',x.id)"><Trash2 :size="15" class="text-red-400"/></button></div></div></section>
    </div>
  </div>
</template>
